version: '3'

services:
  todo-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
  
  todo-app:
    build:
      context: .
      dockerfile: go_api/Dockerfile
    container_name: todo-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://todo-mysql:3306/todo_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
    ports:
      - "8080:8080"
