version: '3'

services:
  todo_mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: todo-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  todo-app:
    build:
      context: .
      dockerfile: go_api/Dockerfile
    volumes:
      - ./go_api:/go/src/app
    container_name: todo-app
    environment:
      DB_USERNAME: root
      DB_PASSWORD: DB_PASSWORD
      DB_HOSTNAME: todo_mysql
      DB_PORT: 3306
      DB_DBNAME: todo_db
    ports:
      - "8080:8080"
    depends_on:
      - todo_mysql
